### ISSUE TITLE
Облегченная прошивка для atmega 168

### ISSUE THREAD

**Issue by MisTERR0000** [AlexGyver/PCdisplay#12]
Запрашиваю создание облегченной прошивки, в которой будет только показ значений внутренних датчиков и аптайма системы. Возможно, если поместится - внешний датчик температуры. Скетч пригодится тем, кто не хочет забивать гвозди микроскопом и использовать только самое необходимое из этого проекта.

В нижеприведенном скетче я постарался выпилить все что относится к вентиляторам, температуре и подсветке. Навыками программирования не обладаю. Удалял методом проб и ошибок.  Требуется нормальная доработка. 

[PCdisplay_foratm168_v.1.3.txt](https://github.com/AlexGyver/PCdisplay/files/1625761/PCdisplay_foratm168_v.1.3.txt)

**Comment by MisTERR0000** [comment]
Попытался попилить исходную прошивку самостоятельно. 

Убраны:
1) Заставка перед включением
2) 7я страница показаний
3) Дебаг-режим

В результате скетч получился недостаточно миниатюрным, но, к сожалению в C# я не силен.
Скетч использует 9678 байт (67%) памяти устройства.
Глобальные переменные используют 884 байт (86%) динамической памяти, оставляя 140 байт для локальных переменных.
Недостаточно памяти, программа может работать нестабильно.
Также для того чтобы выкинуть из скетча RGB и вентиляторы, как я понял, необходимо пилить не только скетч, но и сам OHM

[PCdisplay_micro_v.1.0.txt](https://github.com/AlexGyver/PCdisplay/files/1648500/PCdisplay_micro_v.1.0.txt)

**Comment by 1271** [comment]
**Недостаточно памяти, программа может работать нестабильно.**
Не обращайте внимания на данную строку. Все должно работать хорошо.

**к сожалению в C# я не силен.**
Arduino использует код на С, а не на C#

**Также для того чтобы выкинуть из скетча RGB и вентиляторы, как я понял, необходимо пилить не только скетч, но и сам OHM**
В корне неверно. Достаточно поправить скетч ардуины. Количество приходящих данных для Вас не важно. Берите только свои.

**Comment by MisTERR0000** [comment]
Тогда скажу несколько проще - я вообще не силен в программировани. 
Пока, при удалении кода, связанного с RGB (как я вижу, он занимает больше всего места в скетче), весь скетч крашится.

**Comment by 1271** [comment]
Тогда сейчас.

**Comment by MisTERR0000** [comment]
А под 2004 низя? Хотя, в принципе, мой скетч недалеко ушел по объемам, так что для 2004 можно использовать и мой, просто он не так чист как у товарища 1271

**Comment by 1271** [comment]
Ох. Не заметил, что Вы используете 2004 версию дисплея.
После работы залью для 2004.

**Comment by 1271** [comment]
Добавил еще файл по ссылке выше.
Не пробовал заливать, но компиляция ошибок не дает.
Удалена работа с датчиком температуры, вентиляторы, таймер секунд/минут/часов.

Скетч использует 9130 байт (63%) памяти устройства. Всего доступно 14336 байт.
Глобальные переменные используют 865 байт (84%) динамической памяти, оставляя 159 байт для локальных переменных. Максимум: 1024 байт.
_Недостаточно памяти, программа может работать нестабильно._

На предостережение можете не обращать внимания. Все должно работать корректно.

**Comment by MisTERR0000** [comment]
Спасибо огромное за труд！
