### ISSUE TITLE
OLED Display 

### ISSUE THREAD

**Issue by nick7zmail** [AlexGyver/PCdisplay#15]
Алекс, сделай пожалуйста адаптацию для oled-дисплеев формата 128х64 и 128х32.

**Comment by 1271** [comment]
Это совсем другой тип дисплея. Не думаю, что автор будет это делать.
Хотя, если появится желание/время, м.б. я сделаю. (Шанс есть, но он мал. Ибо я ленив)

**Comment by nick7zmail** [comment]
Я почти доделал...по крайней мере основной экран точно есть)) надо хотя бы второй экран допилить, потом пулл реквест залью. Мож кто доработать графики (лично мне они как-то не нужны))

**Comment by nick7zmail** [comment]
https://github.com/AlexGyver/PCdisplay/pull/16 
Вопрос, полагаю, закрыт. Хотя не помешало бы для дисплеев 128x32 ещё сделать скетч.
