### ISSUE TITLE
Температура

### ISSUE THREAD

**Issue by azzAZZ1** [AlexGyver/PCdisplay#2]
Программа не отображает (и не выводит в com) температуру cpu и gpu, но версия, скачанная с оф. сайта корректно отображает все.

**Comment by 1271** [comment]
Здравствуйте. Раз автор ничего не ответил, то позвольте мне.
Вечером, после работы, посмотрю, в чем проблема.

**Comment by azzAZZ1** [comment]
В общем автор использует старую версию программы. Я не силен в программировании, но попытался переделать последнюю версию. В общем температура проца начала отображаться, но видеокарты нет( видимо из-за того что я юзаю ноут (gtx940mx)), но сама программа выпадает в ошибку. Интересный факт, если не закрывать ошибку, то данные в порт все равно передаются.

**Comment by 1271** [comment]
Ну, сейчас поковыряю.
Если получится, скину ссылку на обновленную версию сюда и сделаю пул-реквест

**Comment by azzAZZ1** [comment]
P.S. Да, новая версия все отображает.
"но видеокарты нет" - сама прога отображает температуру видео?
Нет, но другие программы типо aida64 отображают.
P.P.S.
Так, все работает. Ошибок не наблюдаю.
Я пытался сам собирать программу из исходников, но с файлами отвечающих за Serial port, которые я взял из исходников здесь. Serial заработал исправно, но если прокрутить список устройств в программе она выдает ошибку, но продолжает работать.

**Comment by 1271** [comment]
Попробуйте версию из пул-реквеста

**Comment by azzAZZ1** [comment]
"Это уже к автору OpenHardwareMonitor." - Это да. Последняя версия 2016 года.
Ваша программа работает идеально. Спасибо.
